#= require underscore.string

push_event = ->
  $body = $("body")
  userid = $body.data("userid")

  if userid
    Pusher.log = (message) ->
      if window.console and window.console.log
        window.console.log message
      return

    pusher = new Pusher('e7d1b74dd30352eddd81')
    channel = pusher.subscribe('user_' + userid)

    channel.bind 'chat_event', (data) ->
      #var messagelog = document.getElementById('messagelog');
      #var messagediv = document.createElement('div');
      #messagediv.innerHTML = data.message;
      #messagelog.appendChild(messagediv);
        console.log data.message.body
      return
    return
  else
    console.log "not logged in"
  return

$(document).ready push_event
$(document).on 'page:load', push_event

# ---
# generated by js2coffee 2.0.4